#!/bin/bash

set -e

mkdir -p log {scrape,produce}/{in,cmd}

rm -rf {scrape,produce}"/in/query.txt" "produce/in/url"

ln -s ../../query.txt "scrape/in/query.txt"
ln -s ../../query.txt "produce/in/query.txt"
ln -s ../../scrape/out/url "produce/in/url"

if [ ! -e config.py ] ; then cp /usr/lib/webgetpics/config.py . ; fi
if [ ! -e query.txt ] ; then cp /usr/lib/webgetpics/query.txt . ; fi

python2 -B /usr/lib/webgetpics/scrape.py &>>log/scrape.log &
SCRAPE=$!
python2 -B /usr/lib/webgetpics/produce.py &>>log/produce.log &
PRODUCE=$!

function onquit() {
  trap "" SIGINT SIGTERM
  echo "Quitting." ;
  touch {produce,scrape}/cmd/quit
  wait $SCRAPE $PRODUCE
}

trap onquit SIGINT SIGTERM
echo "Serving."
wait $SCRAPE $PRODUCE
